language: go

go:
- 1.13.x

script:
- export GO111MODULE=on
- go test -v ./...

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
